export const TYPES_FOR_POST = {
  FETCH_ALL: "FETCH_ALL_POST",
  CREATE: "CREATE_POST",
  UPDATE: "UPDATE_POST",
  LIKE: "LIKE_POST",
  DELETE: "DELETE_POST",
};

export const TYPES_FOR_USERS = {
  AUTH: "AUTH_USER",
  LOGOUT: "LOGOUT_USER",
  GOOGLE_LOGIN: "GOOGLE_SIGN_IN_SIGNUP",
};
